Problem 9
silkeh/euler pull request #8
Opened 2020-10-06 13:54 UTC by Achilleshiel

Depends on #7

2020-10-10 18:27 UTC, silkeh requested changes

2020-10-10 18:27 UTC, silkeh commented on filter/condition/equal.go
> +type Equal struct {
Private :)

2020-10-10 18:27 UTC, silkeh commented on filter/coprime.go
> +type Coprime struct {
```suggestion
type Coprime struct {}
```

2020-10-10 18:27 UTC, silkeh commented on filter/coprime.go
> +			//fmt.Printf("Coprime: %d, %d\n",v1,v2)
No ~~capes~~ commented out code!

2020-10-10 18:27 UTC, silkeh commented on filter/pythagorean_tripleter.go
> +type PythagoreanTripleter struct {
Make private

2020-10-10 18:27 UTC, silkeh commented on filter/pythagorean_tripleter.go
> +			//fmt.Printf("triplet: %d, %d, %d\n", a, b, c)
:expressionless:

2020-10-10 18:27 UTC, silkeh commented on filter/sequence_sum.go
> +type SequenceSum struct {
Make private!

2020-10-10 18:27 UTC, silkeh commented on generator/double_sequence.go
> +type DoubleSequence struct {
Make private!

2020-10-11 12:50 UTC, Achilleshiel commented on filter/pythagorean_tripleter.go
> +			//fmt.Printf("triplet: %d, %d, %d\n", a, b, c)
:see_no_evil:

2020-10-23 19:31 UTC, silkeh approved these changes

2020-10-28 12:01 UTC, merged

2020-10-28 12:01 UTC, silkeh commented
LGTM, thanks!